// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: 2021-11-26T09:27:01Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/mises-id/storagesvc/proto"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	ImageUrlEndpoint endpoint.Endpoint
	FUploadEndpoint  endpoint.Endpoint
	UploadEndpoint   endpoint.Endpoint
}

// Endpoints

func (e Endpoints) ImageUrl(ctx context.Context, in *pb.ImageUrlRequest) (*pb.ImageUrlResponse, error) {
	response, err := e.ImageUrlEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ImageUrlResponse), nil
}

func (e Endpoints) FUpload(ctx context.Context, in *pb.FUploadRequest) (*pb.FUploadResponse, error) {
	response, err := e.FUploadEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.FUploadResponse), nil
}

func (e Endpoints) Upload(ctx context.Context, in *pb.UploadRequest) (*pb.UploadResponse, error) {
	response, err := e.UploadEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.UploadResponse), nil
}

// Make Endpoints

func MakeImageUrlEndpoint(s pb.StoragesvcServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ImageUrlRequest)
		v, err := s.ImageUrl(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeFUploadEndpoint(s pb.StoragesvcServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.FUploadRequest)
		v, err := s.FUpload(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeUploadEndpoint(s pb.StoragesvcServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.UploadRequest)
		v, err := s.Upload(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"ImageUrl": {},
		"FUpload":  {},
		"Upload":   {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "ImageUrl" {
			e.ImageUrlEndpoint = middleware(e.ImageUrlEndpoint)
		}
		if inc == "FUpload" {
			e.FUploadEndpoint = middleware(e.FUploadEndpoint)
		}
		if inc == "Upload" {
			e.UploadEndpoint = middleware(e.UploadEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"ImageUrl": {},
		"FUpload":  {},
		"Upload":   {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "ImageUrl" {
			e.ImageUrlEndpoint = middleware("ImageUrl", e.ImageUrlEndpoint)
		}
		if inc == "FUpload" {
			e.FUploadEndpoint = middleware("FUpload", e.FUploadEndpoint)
		}
		if inc == "Upload" {
			e.UploadEndpoint = middleware("Upload", e.UploadEndpoint)
		}
	}
}
