// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: 2021-11-26T09:27:01Z

package main

import (
	"context"
	"flag"
	"fmt"
	"time"

	// This Service
	"github.com/mises-id/sns-storagesvc/handlers"
	"github.com/mises-id/sns-storagesvc/lib/db"
	"github.com/mises-id/sns-storagesvc/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	fmt.Println("mongo init")
	db.SetupMongo(ctx)
	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
